Repository fzaninotto/Faker, pull requests merged in 2019-09, with the labels that each got.

#1779 Enhancement: Add issue template for bug report
  .github/ISSUE_TEMPLATE/bug.md
Labels: enhancement

#1781 Added batch inserts for doctrine orm populate
  readme.md
  src/Faker/ORM/Doctrine/Populator.php
Labels: bug

#1747 Add lastName gender specific on ru_RU locale
  src/Faker/Provider/ru_RU/Person.php
  test/Faker/Provider/ru_RU/PersonTest.php
Labels: enhancement

#1788 Add mobileNumber() method for nb_NO
  readme.md
  src/Faker/Provider/nb_NO/PhoneNumber.php
  test/Faker/Provider/nb_NO/PhoneNumberTest.php
Labels: enhancement

#1575 Prevent Transliterator class autoloading
  src/Faker/Provider/Internet.php
Labels: bug

#1514 Document randomDigitNot base formatter.
  readme.md
  src/Faker/Generator.php
Labels: enhancement

#1434 Taiwan ID. The initial letter must be a capital letter. p->P
  src/Faker/Provider/zh_TW/Person.php
Labels: bug

#1459 Fixing sk_SK men last names set
  src/Faker/Provider/sk_SK/Person.php
Labels: bug

#1754 add id_ID Color
  src/Faker/Provider/id_ID/Color.php
Labels: enhancement, help wanted

#1789 typo
  src/Faker/Provider/Uuid.php
Labels: bug

#1658 Bug Fix en_SG mobile number generation
  src/Faker/Provider/en_SG/PhoneNumber.php
  test/Faker/Provider/en_SG/PhoneNumberTest.php
Labels: bug

#1790 Floor is not always returning an int
  src/Faker/Provider/Biased.php
Labels: bug

#1783 Enhancement: Slightly clean up Company provider
  src/Faker/Provider/Company.php
  src/Faker/Provider/nl_NL/Company.php
Labels: enhancement

#1590 Refactoring of the TextTest class
  test/Faker/Provider/TextTest.php
Labels: enhancement
