Repository fzaninotto/Faker, pull requests merged in 2019-11, with the labels that each got.

#1537 Portuguese providers for Companies and Internet
  src/Faker/Provider/pt_PT/Company.php
  src/Faker/Provider/pt_PT/Internet.php
Labels: enhancement

#1451 add birthplace support for ID nik generator
  src/Faker/Provider/id_ID/Person.php
  test/Faker/Provider/id_ID/PersonTest.php
Labels: enhancement

#1595 Fix method name for en_NZ provider in readme
  readme.md
Labels: enhancement

#1836 Release/1.9.0
  CHANGELOG.md
  test/Faker/Provider/ImageTest.php
Labels: enhancement

#1843 Curly braces for arrays is deprecated in PHP 7.4
  src/Faker/Calculator/Luhn.php
  test/Faker/Provider/fi_FI/PersonTest.php
  test/Faker/Provider/sv_SE/PersonTest.php
Labels: bug, enhancement

#1834 Add link to PHPStan extension to readme
  readme.md
Labels: enhancement

#1822 Enhancement: Configure verbose output via phpunit.xml.dist
  Makefile
  phpunit.xml.dist
Labels: enhancement

#1819 Fix: Remove unnecessary class-level DocBlocks
  src/Faker/Provider/en_NG/Person.php
  test/Faker/Provider/ProviderOverrideTest.php
  test/Faker/Provider/es_VE/CompanyTest.php
  test/Faker/Provider/es_VE/PersonTest.php
Labels: bug

#1823 Enhancement: Use all columns when running tests
  phpunit.xml.dist
Labels: enhancement

#1858 Enhancement: Echo a greeting
  .github/workflows/continuous-integration.yml
Labels: enhancement

#1824 Enhancement: Collect code coverage
  .gitignore
  .travis.yml
  .travis/xdebug.sh
  Makefile
  phpunit.xml.dist
  readme.md
Labels: enhancement
