Repository fzaninotto/Faker, pull requests merged in 2020-10, with the labels that each got.

#1985 Added missing properties in doc-block
  src/Faker/Generator.php
Labels: bug

#2018 Replace latin 'a' letter to cyrillic 'а' letter
  src/Faker/Provider/ru_RU/Person.php
Labels: bug

#2073 Enhancement: Update actions/checkout
  .github/workflows/continuous-integration.yml
Labels: dependency

#2074 Enhancement: Update actions/cache
  .github/workflows/continuous-integration.yml
Labels: dependency

#2075 Fix: Update phpunit/phpunit
  composer.json
  composer.lock
Labels: dependency

#2045 Fix letter 'a' in female lastname generation (ru_RU)
  src/Faker/Provider/ru_RU/Person.php
  test/Faker/Provider/ru_RU/PersonTest.php
Labels: bug

#2076 Fix: Update squizlabs/php_codesniffer
  composer.json
  composer.lock
  src/Faker/Provider/ar_SA/Color.php
  src/Faker/Provider/at_AT/Payment.php
  src/Faker/Provider/en_IN/Address.php
  src/Faker/Provider/en_IN/Person.php
  src/Faker/Provider/en_NG/PhoneNumber.php
  src/Faker/Provider/en_PH/PhoneNumber.php
  src/Faker/Provider/es_PE/Person.php
  src/Faker/Provider/fa_IR/PhoneNumber.php
  src/Faker/Provider/fi_FI/Person.php
  src/Faker/Provider/ka_GE/Text.php
  src/Faker/Provider/ko_KR/PhoneNumber.php
  src/Faker/Provider/ms_MY/Address.php
  src/Faker/Provider/ms_MY/Person.php
  src/Faker/Provider/nl_BE/Person.php
  src/Faker/Provider/nl_NL/Address.php
  src/Faker/Provider/nl_NL/Person.php
  src/Faker/Provider/pt_BR/Address.php
  src/Faker/Provider/ru_RU/Address.php
  src/Faker/Provider/ru_RU/Text.php
  src/Faker/Provider/sv_SE/Company.php
  src/Faker/Provider/th_TH/Address.php
  src/Faker/Provider/zh_CN/Person.php
  test/Faker/Calculator/LuhnTest.php
  test/Faker/Provider/ImageTest.php
  test/Faker/Provider/PaymentTest.php
  test/Faker/Provider/en_GB/AddressTest.php
  test/Faker/Provider/en_NG/AddressTest.php
  test/Faker/Provider/ru_RU/PersonTest.php
Labels: dependency

#1965 Enhancement: Raise error level from 7 to 6
  psalm-baseline.xml
  psalm.xml
  src/Faker/Calculator/Luhn.php
  src/Faker/Provider/Barcode.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/PhoneNumber.php
  src/Faker/Provider/ar_SA/Address.php
  src/Faker/Provider/is_IS/Person.php
  src/Faker/Provider/ja_JP/Text.php
  src/Faker/Provider/pl_PL/Company.php
  src/Faker/Provider/pl_PL/Person.php
  src/Faker/Provider/pt_BR/check_digit.php
  test/Faker/Provider/DateTimeTest.php
  test/Faker/Provider/bn_BD/PersonTest.php
  test/Faker/Provider/en_SG/AddressTest.php
  test/Faker/Provider/es_ES/PersonTest.php
  test/Faker/Provider/es_ES/PhoneNumberTest.php
  test/Faker/Provider/fr_FR/PaymentTest.php
  test/Faker/Provider/id_ID/PersonTest.php
  test/Faker/Provider/it_IT/CompanyTest.php
  test/Faker/Provider/it_IT/PersonTest.php
  test/Faker/Provider/kk_KZ/CompanyTest.php
  test/Faker/Provider/kk_KZ/PersonTest.php
  test/Faker/Provider/pt_BR/CompanyTest.php
  test/Faker/Provider/pt_BR/PersonTest.php
  test/Faker/Provider/pt_PT/PersonTest.php
  test/Faker/Provider/pt_PT/PhoneNumberTest.php
  test/Faker/Provider/ro_RO/PhoneNumberTest.php
Labels: enhancement

#2078 Enhancement: Add configuration for Dependabot
  .github/dependabot.yaml
Labels: dependency

#2082 Enhancement: Raise error level from 6 to 5
  psalm.xml
  src/Faker/Factory.php
  src/Faker/Guesser/Name.php
  src/Faker/Provider/File.php
Labels: enhancement

#2072 Enhancement: Update vimeo/psalm
  composer.json
  composer.lock
  psalm-baseline.xml
Labels: dependency

#2080 Enhancement: Update dealerdirect/phpcodesniffer-composer-installer
  composer.json
  composer.lock
Labels: blocking, dependency

#2083 Enhancement: Add configuration for Dependabot
  .github/dependabot.yaml
Labels: enhancement

#2081 Enhancement: Update slevomat/coding-standard
  composer.json
  composer.lock
Labels: blocking, dependency

#2086 Enhancement: Enable UnusedUses rule
  phpcs.xml
  src/Faker/Provider/ms_MY/Address.php
  src/Faker/Provider/ms_MY/Person.php
  test/Faker/Provider/BaseTest.php
  test/Faker/Provider/nl_BE/PersonTest.php
Labels: enhancement

#2087 Fix: Remove psalm/plugin-phpunit
  composer.json
  composer.lock
  psalm.xml
Labels: blocking, bug

#2089 Fix: PHP requirement in README.md
  readme.md
Labels: bug

#2090 Enhancement: Allow installation with PHP 8.0
  composer.json
Labels: enhancement
