Repository fzaninotto/Faker, pull requests merged in 2020-03, with the labels that each got.

#1892 Fix: Invoke composer directly
  .github/workflows/continuous-integration.yml
Labels: bug

#1893 Fix: Configure preferred installation method via composer.json
  Makefile
  composer.json
Labels: bug

#1895 Enhancement: Update squizlabs/php_codesniffer
  composer.json
  src/Faker/Provider/el_GR/Text.php
Labels: enhancement

#1896 Enhancement: Use XML configuration for squizlabs/php_codesniffer
  .gitattributes
  .github/workflows/continuous-integration.yml
  Makefile
  phpcs.xml
Labels: enhancement

#1953 Enhancement: Add note about 'Keep a Changelog'
  CHANGELOG.md
Labels: enhancement

#1898 Fix: Use extensions key instead of deprecated extension-csv
  .github/workflows/continuous-integration.yml
Labels: blocking, bug

#1927 Fix typo
  src/Faker/Calculator/TCNo.php
Labels: bug

#1955 Fix: Show build status for next branch
  readme.md
Labels: bug

#1957 Removed all the ORM/ODM integrations from the core
  CHANGELOG.md
  readme.md
  src/Faker/ORM/CakePHP/ColumnTypeGuesser.php
  src/Faker/ORM/CakePHP/EntityPopulator.php
  src/Faker/ORM/CakePHP/Populator.php
  src/Faker/ORM/Doctrine/ColumnTypeGuesser.php
  src/Faker/ORM/Doctrine/EntityPopulator.php
  src/Faker/ORM/Doctrine/Populator.php
  src/Faker/ORM/Mandango/ColumnTypeGuesser.php
  src/Faker/ORM/Mandango/EntityPopulator.php
  src/Faker/ORM/Mandango/Populator.php
  src/Faker/ORM/Propel/ColumnTypeGuesser.php
  src/Faker/ORM/Propel/EntityPopulator.php
  src/Faker/ORM/Propel/Populator.php
  src/Faker/ORM/Propel2/ColumnTypeGuesser.php
  src/Faker/ORM/Propel2/EntityPopulator.php
  src/Faker/ORM/Propel2/Populator.php
  src/Faker/ORM/Spot/ColumnTypeGuesser.php
  src/Faker/ORM/Spot/EntityPopulator.php
  src/Faker/ORM/Spot/Populator.php
Labels: enhancement

#1958 Enhancement: Collect code coverage using pcov
  .github/workflows/continuous-integration.yml
Labels: enhancement

#1954 Enhancement: Run builds on master using GitHub Actions
  .gitattributes
  .github/workflows/continuous-integration.yml
  .travis.yml
  .travis/xdebug.sh
  readme.md
Labels: enhancement

#1959 Enhancement: Synchronize workflow
  .github/workflows/continuous-integration.yml
Labels: enhancement

#1879 Remove Persian (fa_IR) rude words.
  src/Faker/Provider/fa_IR/Text.php
Labels: bug

#1961 Fix: Remove deprecated curly braces
  src/Faker/Calculator/Luhn.php
  test/Faker/Provider/fi_FI/PersonTest.php
  test/Faker/Provider/sv_SE/PersonTest.php
Labels: bug

#1956 Project specific files
  .editorconfig
  .gitattributes
  .github/workflows/continuous-integration.yml
  .gitignore
  composer.json
  composer.lock
Labels: enhancement

#1894 Enhancement: Add type and return type declarations to Generator
  src/Faker/Generator.php
Labels: enhancement

#1897 Enhancement: Run a static code analysis and collect type coverage with vimeo/psalm
  .gitattributes
  .github/workflows/continuous-integration.yml
  Makefile
  composer.json
  psalm-baseline.xml
  psalm.xml
  readme.md
  src/Faker/Provider/Base.php
  src/Faker/Provider/cs_CZ/Person.php
  src/Faker/Provider/is_IS/Address.php
  src/Faker/Provider/me_ME/Payment.php
  src/Faker/Provider/pl_PL/Person.php
  test/Faker/Provider/de_CH/AddressTest.php
  test/Faker/Provider/de_CH/InternetTest.php
  test/Faker/Provider/de_CH/PhoneNumberTest.php
  test/Faker/Provider/en_AU/AddressTest.php
  test/Faker/Provider/en_CA/AddressTest.php
  test/Faker/Provider/en_IN/AddressTest.php
  test/Faker/Provider/en_NZ/PhoneNumberTest.php
  test/Faker/Provider/en_PH/AddressTest.php
  test/Faker/Provider/en_UG/AddressTest.php
  test/Faker/Provider/fr_CH/AddressTest.php
  test/Faker/Provider/fr_CH/InternetTest.php
  test/Faker/Provider/fr_CH/PhoneNumberTest.php
  test/Faker/Provider/fr_FR/AddressTest.php
  test/Faker/Provider/it_CH/AddressTest.php
  test/Faker/Provider/it_CH/InternetTest.php
  test/Faker/Provider/it_CH/PhoneNumberTest.php
  test/Faker/Provider/pt_PT/PersonTest.php
Labels: enhancement

#1963 Fix: Update composer.lock
  composer.lock
Labels: bug

#1962 Migrated Faker to match PSR12 instead of PSR2
  phpcs.xml
  src/Faker/Calculator/Inn.php
  src/Faker/Documentor.php
  src/Faker/Guesser/Name.php
  src/Faker/Provider/Barcode.php
  src/Faker/Provider/Base.php
  src/Faker/Provider/DateTime.php
  src/Faker/Provider/File.php
  src/Faker/Provider/Image.php
  src/Faker/Provider/Internet.php
  src/Faker/Provider/Lorem.php
  src/Faker/Provider/Text.php
  src/Faker/Provider/el_GR/Company.php
  src/Faker/Provider/en_US/Payment.php
  src/Faker/Provider/fa_IR/Text.php
  src/Faker/Provider/fi_FI/Person.php
  src/Faker/Provider/fr_FR/Person.php
  src/Faker/Provider/is_IS/Person.php
  src/Faker/Provider/kk_KZ/Person.php
  src/Faker/Provider/lt_LT/Person.php
  src/Faker/Provider/ms_MY/Address.php
  src/Faker/Provider/ms_MY/Person.php
  src/Faker/Provider/nb_NO/Person.php
  src/Faker/Provider/nl_BE/Person.php
  src/Faker/Provider/pl_PL/Person.php
  src/Faker/Provider/pt_BR/Company.php
  src/Faker/Provider/pt_BR/Person.php
  src/Faker/Provider/pt_BR/PhoneNumber.php
  src/Faker/Provider/pt_BR/check_digit.php
  src/Faker/Provider/pt_PT/Person.php
  src/Faker/Provider/ro_MD/Address.php
  src/Faker/Provider/ro_MD/Person.php
  src/Faker/Provider/ro_RO/Address.php
  src/Faker/Provider/ro_RO/Person.php
  src/Faker/Provider/zh_TW/Address.php
  src/Faker/UniqueGenerator.php
Labels: enhancement

#1964 Enhancement: Require error level 7
  psalm.xml
Labels: enhancement

#1967 Enhancement: Show progress when running phpcbf or phpcs
  phpcs.xml
Labels: enhancement

#1969 Enhancement: Reference schema for phpcs configuration
  phpcs.xml
Labels: enhancement

#1970 Enhancement: Use cache for squizlabs/php_codesniffer
  .github/workflows/continuous-integration.yml
  Makefile
Labels: enhancement
